// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRcKSKNQBr-LYuaMHSufhg3xJ3UuQMo2c',
    appId: '1:694949898753:android:0259add168620ba92dae00',
    messagingSenderId: '694949898753',
    projectId: 'finalyearproject-45e32',
    storageBucket: 'finalyearproject-45e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuwRwrbTbWStu3JAwhmZQnsbmsMdZH13o',
    appId: '1:694949898753:ios:c43833bfcb1fd59d2dae00',
    messagingSenderId: '694949898753',
    projectId: 'finalyearproject-45e32',
    storageBucket: 'finalyearproject-45e32.firebasestorage.app',
    androidClientId: '694949898753-i29k0ru4bi2f9v0crl93r5jtbjqd9de4.apps.googleusercontent.com',
    iosClientId: '694949898753-5ggkst3hduobmgvmpbdn86ibn8vat0kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualTryonMakeup',
  );

}